# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: DevOpsGO
description: > # this means to ignore newlines until "baseurl:"
    Grupo DevOps de Goiás
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://devopsgo.github.io/" # the base hostname & protocol for your site
twitter_username: devopsgo
github_username: DevOpsGO
google_group: devopsgo
facebook_group: devopsgo
slack_company: devopsgo

# Build settings
markdown: kramdown
